/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPermissionsRouteImport } from './routes/dashboard.permissions'
import { Route as DashboardLeaderboardRouteImport } from './routes/dashboard.leaderboard'
import { Route as DashboardIntelligenceRouteImport } from './routes/dashboard.intelligence'
import { Route as DashboardDeveloperRouteImport } from './routes/dashboard.developer'
import { Route as DashboardCredentialsRouteImport } from './routes/dashboard.credentials'
import { Route as DashboardAnalyzerRouteImport } from './routes/dashboard.analyzer'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPermissionsRoute = DashboardPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeaderboardRoute = DashboardLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntelligenceRoute = DashboardIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeveloperRoute = DashboardDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCredentialsRoute = DashboardCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyzerRoute = DashboardAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/verify': typeof VerifyRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/analyzer': typeof DashboardAnalyzerRoute
  '/dashboard/credentials': typeof DashboardCredentialsRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify': typeof VerifyRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/analyzer': typeof DashboardAnalyzerRoute
  '/dashboard/credentials': typeof DashboardCredentialsRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/verify': typeof VerifyRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/analyzer': typeof DashboardAnalyzerRoute
  '/dashboard/credentials': typeof DashboardCredentialsRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/permissions': typeof DashboardPermissionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/verify'
    | '/dashboard/activity'
    | '/dashboard/analyzer'
    | '/dashboard/credentials'
    | '/dashboard/developer'
    | '/dashboard/intelligence'
    | '/dashboard/leaderboard'
    | '/dashboard/permissions'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify'
    | '/dashboard/activity'
    | '/dashboard/analyzer'
    | '/dashboard/credentials'
    | '/dashboard/developer'
    | '/dashboard/intelligence'
    | '/dashboard/leaderboard'
    | '/dashboard/permissions'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/verify'
    | '/dashboard/activity'
    | '/dashboard/analyzer'
    | '/dashboard/credentials'
    | '/dashboard/developer'
    | '/dashboard/intelligence'
    | '/dashboard/leaderboard'
    | '/dashboard/permissions'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/permissions': {
      id: '/dashboard/permissions'
      path: '/permissions'
      fullPath: '/dashboard/permissions'
      preLoaderRoute: typeof DashboardPermissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leaderboard': {
      id: '/dashboard/leaderboard'
      path: '/leaderboard'
      fullPath: '/dashboard/leaderboard'
      preLoaderRoute: typeof DashboardLeaderboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/intelligence': {
      id: '/dashboard/intelligence'
      path: '/intelligence'
      fullPath: '/dashboard/intelligence'
      preLoaderRoute: typeof DashboardIntelligenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/developer': {
      id: '/dashboard/developer'
      path: '/developer'
      fullPath: '/dashboard/developer'
      preLoaderRoute: typeof DashboardDeveloperRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/credentials': {
      id: '/dashboard/credentials'
      path: '/credentials'
      fullPath: '/dashboard/credentials'
      preLoaderRoute: typeof DashboardCredentialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analyzer': {
      id: '/dashboard/analyzer'
      path: '/analyzer'
      fullPath: '/dashboard/analyzer'
      preLoaderRoute: typeof DashboardAnalyzerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardAnalyzerRoute: typeof DashboardAnalyzerRoute
  DashboardCredentialsRoute: typeof DashboardCredentialsRoute
  DashboardDeveloperRoute: typeof DashboardDeveloperRoute
  DashboardIntelligenceRoute: typeof DashboardIntelligenceRoute
  DashboardLeaderboardRoute: typeof DashboardLeaderboardRoute
  DashboardPermissionsRoute: typeof DashboardPermissionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardAnalyzerRoute: DashboardAnalyzerRoute,
  DashboardCredentialsRoute: DashboardCredentialsRoute,
  DashboardDeveloperRoute: DashboardDeveloperRoute,
  DashboardIntelligenceRoute: DashboardIntelligenceRoute,
  DashboardLeaderboardRoute: DashboardLeaderboardRoute,
  DashboardPermissionsRoute: DashboardPermissionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
